# fly.toml app configuration file generated for ip-project on 2024-03-13T17:44:00+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ip-project'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  mac_machines_running = 1
  processes = ['app']

[[services.ports]]
  handlers = ["tls"]
  port = "443"
  tls_options = { alpn = ["h2", "http/1.1"] }

[http_service.http_options]
  h2_backend = true

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
